<?php use Phalcon\Tag; ?>

<h2>Sign up using this form</h2>

<?php echo Tag::form(array("signup/register","class"=>"form-horizontal","role"=>"form")); ?>
<div class="form-group">
  <label for="name" class="col-sm-2 control-label">Name</label>
  <div class="col-sm-10"><?php echo Tag::textField(array("name","class"=>"form-control")); ?></div>
</div>
<div class="form-group">
  <label for="email" class="col-sm-2 control-label">E-Mail</label>
  <div class="col-sm-10"><?php echo Tag::textField(array("email","class"=>"form-control")); ?></div>
</div>
<div class="form-group">
  <label for="email" class="col-sm-2 control-label">&nbsp;</label>
  <div class="col-sm-10"><?php echo Tag::submitButton(array("Register","class"=>"btn btn-default btn-primary"));?></div>
</div>


</form>