<?php use Phalcon\Tag; 
$url = new Phalcon\Mvc\Url();
?>

<h2><?php echo $page_title; ?></h2>
<p><?php echo $link_return; ?></p>
<form class='form-horizontal' action='/vg/companies/edit/'>
  
    <?php echo Tag::hiddenField(array("id","value"=>$company->id)); ?>
  
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10"><?php echo Tag::textField(array("name","class"=>"form-control","maxlength"=>"100","value"=>$company->name)); ?></div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Country</label>
    <div class="col-sm-10"><?php echo Tag::textField(array("country","class"=>"form-control","maxlength"=>"2","value"=>$company->country)); ?></div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Wiki Link</label>
    <div class="col-sm-10"><?php echo Tag::textField(array("wiki_link","class"=>"form-control","maxlength"=>"100","value"=>$company->wiki_link)); ?></div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">URL</label>
    <div class="col-sm-10"><?php echo Tag::textField(array("url","class"=>"form-control","maxlength"=>"100","value"=>$company->url)); ?></div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Year Founded</label>
    <div class="col-sm-10"><?php echo Tag::textField(array("year_founded","class"=>"form-control","maxlength"=>"4","value"=>$company->year_founded)); ?></div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10"><button class='btn btn-primary btn-submit'>Save</button></div>
  </div>


</form>