<?php use Phalcon\Tag; 
$url = new Phalcon\Mvc\Url();
?>

<h2>Edit Console System</h2>
<p><?php echo Tag::linkTo("systems/show/" . $system->url, "Return to View") ;?></p>
<form class='form-horizontal' action='/vg/systems/edit/'>
  <?php echo Tag::hiddenField(array("id","value"=>$system->id)); ?>
  <div class="row">
    <div class="col-sm-12">
      <h3>System Details</h3>
    </div>
  </div>
  <div class="row">
    
    <div class="col-sm-6">
      
      <div class="form-group">
        <label for="name" class="col-sm-3 control-label">Name:</label>
        <div class="col-sm-9"><?php echo Tag::textField(array("name","class"=>"form-control","maxlength"=>"100","value"=>$system->name)); ?></div>
      </div>
      <div class="form-group">
        <label for="email" class="col-sm-3 control-label">URL:</label>
        <div class="col-sm-9"><?php echo Tag::textField(array("url","class"=>"form-control","maxlength"=>"100","value"=>$system->url)); ?></div>
      </div>
      <div class="form-group">
        <label for="email" class="col-sm-3 control-label">Company:</label>
        <div class="col-sm-9"><?php echo Tag::select(array("id"=>"company_id","name"=>"company_id","value"=>$system->company_id,"class"=>"form-control"), $dropdown_companies); ?></div>
      </div>
      <div class="form-group">
        <label for="email" class="col-sm-3 control-label">Wiki Link:</label>
        <div class="col-sm-9"><?php echo Tag::textField(array("wiki_link","class"=>"form-control","maxlength"=>"100","value"=>$system->wiki_link)); ?></div>
      </div>  
    </div><!--col-x2-2-->
    
    <div class="col-sm-6">
      <div class="form-group">
        <label for="email" class="col-sm-3 control-label">Year:</label>
        <div class="col-sm-9"><?php echo Tag::textField(array("year","class"=>"form-control","maxlength"=>"4","value"=>$system->year)); ?></div>
      </div>
      <div class="form-group">
        <label for="email" class="col-sm-3 control-label">Generation</label>
        <div class="col-sm-9"><?php echo Tag::select(array("id"=>"generation_id","name"=>"generation_id","value"=>$system->generation_id,"class"=>"form-control"), $dropdown_generations); ?></div>
      </div>
      
      <div class="form-group">
        <label for="email" class="col-sm-3 control-label">Units Sold:</label>
        <div class="col-sm-9"><?php echo Tag::textField(array("units_sold","class"=>"form-control","maxlength"=>"11","value"=>$system->units_sold)); ?></div>
      </div>  
      <div class="form-group">
        <label for="email" class="col-sm-3 control-label">Number of Games:</label>
        <div class="col-sm-9"><?php echo Tag::textField(array("num_games","class"=>"form-control","maxlength"=>"10","value"=>$system->num_games)); ?></div>
      </div>          
    </div><!--col-x2-2-->
  </div><!--row-->
  
  

  <h3>Tech Specs</h3>  
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">CPU:</label>
    <div class="col-sm-10"><?php echo Tag::textField(array("cpu","class"=>"form-control","maxlength"=>"50","value"=>$system->cpu)); ?></div>
  </div>
  
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Bytes of RAM:</label>
    <div class="col-sm-10"><?php echo Tag::textField(array("ram_bytes","class"=>"form-control","maxlength"=>"20","value"=>$system->ram_bytes)); ?></div>
  </div>  
  
  
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Media Format:</label>
    <div class="col-sm-10"><?php echo Tag::select(array("id"=>"media_format_id","name"=>"media_format_id","value"=>$system->media_format_id,"class"=>"form-control"), $dropdown_media_formats); ?></div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10"><button class='btn btn-primary btn-submit'>Save</button></div>
  </div>


</form>