<?php 
/*
Main App template
*/
?>
<!DOCTYPE html>
<html>
  <head>
  <script src="/vg/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="/vg/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="/vg/js/common.js" type="text/javascript"></script>
  <link rel="stylesheet" href="/vg/css/bootstrap.min.css" type="text/css"/>
  <link rel="stylesheet" href="/vg/css/bootstrap-theme.min.css" type="text/css"/>
  <link rel="stylesheet" href="/vg/css/style.css" type="text/css"/>
    <title>Example</title>
  </head>
  <body role="document">

  <div class='container'>
    <div class="page-header">
      <h1>Nudd's Videogame Console Database</h1>
    </div>
    
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!--<a class="navbar-brand" href="#">Brand</a>-->
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><?php echo Phalcon\Tag::linkTo("signup", "Sign Up for our Newsletter"); ?></li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Lists <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><?php echo Phalcon\Tag::linkTo("companies", "Companies"); ?></li>
              <li><?php echo Phalcon\Tag::linkTo("systems", "Systems"); ?></li>
              
              <!--<li class="divider"></li>-->
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>    
        <div class='container-message'></div>
        <?php echo $this->getContent() ?>
  </div>
  </body>
</html>